# 2016 April 27
# https://github.com/bevry/base

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
cache:
  directories:
    - node_modules

# Prepare our tests
# Ensure the project is setup correctly and compiled
install: "npm run-script setup"
before_script: "npm run-script compile"

# Run our tests
script: "npm test"

# Custom notifications
notifications:
  slack:
    secure: Jw1XyIGmScouWnHM/eYF2pgb8DKLLp6kiiVrjYAbgewg7CQgfeQoPhVBk6MHhCqfq667QuI4fsyUTLRR0hmFm8cGRwuQ0S2+ugjT2iJZ2746h3haJbo5un8p5xF++dabT52ZNbf+lTSRkw9Ulc7EymlGLU7oICjPPc5TdfmG68w=
  email:
    recipients:
      secure: MeSmPDNHFuwnlz1px07mTZyzc48eJYWZ7iALYjCuh3YsWl97eP2BvSXhggBAHln0s6kyibGiWWzD+Ae0HFNipYlZLit8Wc9SN+L9JLBmekPD6qZTXXxUFH/EG7UstJgTAvn1lcsNS1LvuSqdPVVgUVNzWHUvG+NaGl2IhNQXH/4=
